name: friday
description: Your Personal Class Manager Assistant, It'll never let you miss another assignment deadline or upcoming test.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl:
  provider:
  fluttertoast:
  flutter_svg:
  cupertino_icons:
  cloud_firestore:
  firebase_auth:
  email_validator:
  google_sign_in:
  uuid:
  url_launcher:
  firebase_storage:
  path_provider:
  date_time_picker:
  table_calendar:
  flutter_login_facebook:
  flutter_icons_null_safety:
  firebase_core:
  image_picker:
  shared_preferences: ^2.1.2
  introduction_screen: ^3.1.8
  showcaseview: ^2.0.3
  is_first_run: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
